### ISSUE TITLE
Make  your stats publically available?

### ISSUE THREAD

**Issue by WahidBawa** [Yooooomi/your_spotify#117]
Hey there, I recently set this up on my server and I think it's pretty cool. There is one thing I was wondering.

Is there a way for me to make my stats publicly available after signing in?

For instance, your_spotify is hosted on my server at [https://spotify.yoh.gay](https://spotify.yoh.gay). After I log in on my side, is there a way I can share this same link with my friends and have them be able to see my stats without me having to log in?

If that isn't possible yet I may have a go and try my luck at it.

Thanks.

**Comment by Yooooomi** [comment]
It is a good idea to be able to share your stats since you can't login via password anymore. What process are you thinking about? Something like a link available for 24 hours sounds good what do you think?

Thanks for your feedback! 😃

**Comment by WBawa** [comment]
I was thinking of a more static thing. Like a link that I can leave in my Discord About Me that can show my stats.

As for the technical side of it, I'm thinking that there should be a way to take a snapshot of your stats every so often (once an hour?). We save those stats and whenever someone clicks on the link they'd see the most recent snapshot instead of the most up-to-date version that you see when you're logged in.

I'm only recommending that as I'm not sure how the Spotify API works exactly, so I don't know if it's possible for someone to see my live updated stats externally if that makes sense.

I'm just spitballing here, I'm sure you have some process in mind for making those stats publically available.

**Comment by WahidBawa** [comment]
I was thinking of a more static thing. Like a link that I can leave in my Discord About Me that can show my stats.

As for the technical side of it, I'm thinking that there should be a way to take a snapshot of your stats every so often (once an hour?). We save those stats and whenever someone clicks on the link they'd see the most recent snapshot instead of the most up-to-date version that you see when you're logged in.

I'm only recommending that as I'm not sure how the Spotify API works exactly, so I don't know if it's possible for someone to see my live updated stats externally if that makes sense.

I'm just spitballing here, I'm sure you have some process in mind for making those stats publically available.

**If you got 2 notifications for this, that was because I replied with my work Github by accident LOL**

**Comment by Yooooomi** [comment]
I'm thinking of a token in the link that allows people to check your stats but cannot change any settings. Be careful by making this link available in the future since some stats are really heavy to compute and might slow down your device. That's why I thought of 24 hours links.

**Comment by WahidBawa** [comment]
Maybe add a way to kill the link and generate a new one? I don't foresee my machine having any performance issues but that would be a nice feature.

**Comment by musicderp** [comment]
Looking forward to this feature, recently discovered this app and have been loving it, the ability to share my stats would be awesome!

**Comment by Yooooomi** [comment]
Implemented in the last release! Read the [release](https://github.com/Yooooomi/your_spotify/releases/tag/1.2.0) notes to understand how it works. Feel free to open any issue if you have a problem.
