### ISSUE TITLE
Feature Request: Add SSL support

### ISSUE THREAD

**Issue by maggiknister** [Yooooomi/your_spotify#23]
Hi there! First of all, I like this project a lot.
I have but one simple request: could you enable HTTPS support? I'm running the web app in docker on my homeserver but I think that the container doesn't expose a HTTPS port.
Looking forward to your reply! 😄

**Comment by Yooooomi** [comment]
Hello,

I'm glad to you liked this project :)
To enable SSL, you should simply reverse proxy the application through an nginx or something similar, I am not planning to enable SSL directly into the application since it is not its purpose.

Do not hesitate if you encounter any issue while setting this up :)

**Comment by Yooooomi** [comment]
Since it will not be implemented and it has been created for it to work behind a reverse proxy, I'm going to close it now.
