### ISSUE TITLE
Web does nothing when import "Extended Streaming History"

### ISSUE THREAD

**Issue by kevinlf3** [Yooooomi/your_spotify#398]
Hi, I received my Extended Streaming History from Spotify, 8 JSON files.

![Imagen de WhatsApp 2024-05-12 a las 19 56 55_12d44c19](https://github.com/Yooooomi/your_spotify/assets/69318685/b8b21935-f45f-4a49-9cc6-b051989d5ad5)

But when I select the option to import the Extended History, 1 by 1 or the 8 files all together does nothing, there is a micro refresh but nothing happens, and a green letters told me "Everything looks fine for the import to work".

A few days ago I import the Account Data and everithing was great.

![fa64ee6cf75d320eadc04fbda5c88948](https://github.com/Yooooomi/your_spotify/assets/69318685/1ae78d29-8090-426f-b4ed-2418b7853f7b)

Here is the error:

![Sin título](https://github.com/Yooooomi/your_spotify/assets/69318685/59163907-9791-4653-974d-244ad208bc2c)

What I'm doing wrong? Or what's the problem?

Thanks!

**Comment by MIJmker** [comment]
Hi Kevin, 

CORS (Cross-Origin Resource-Sharing) is blocking the requests. Are the request send from one subdomain to another subdomain? I had the same issue with the API and frontend, so I had to add an environment variable to the docker-compose:
- CORS=spotify.example.com,spotify-api.example.com

This allows both spotify.example.com and spotify-api.example.com to "communicate" in a sense. ofcourse replace those with your actual subdomains.

Hope this helps

**Comment by RagingCactus** [comment]
I'm pretty sure CORS is not the main issue here. Everything else in your installation works, right? You can log in and look at the data in the dashboard? In that case CORS is already configured correctly. It should work out of the box without additional configuration for most deployments.

I assume the root cause is the 413 "Payload Too Large" error. CORS might not work properly as the request is already blocked/dropped because the request exceeds the size limit. This in itself might be worth looking into, but I suspect this is not the root cause.

I _think_ the current code in YourSpotify limits _each individual file_ to 20 MB so it should work:
https://github.com/Yooooomi/your_spotify/blob/7f7f8842ae667d5be385a58e957aa65e1cc10f72/apps/server/src/routes/importer.ts#L20-L26

Are you using any kind of reverse proxy or web server in front of YourSpotify that might restrict the file size further?

**Comment by Yooooomi** [comment]
Hello, are you using linuxserver image?

**Comment by kevinlf3** [comment]
> Hello, are you using linuxserver image?

No, i'm using your image:

![image](https://github.com/Yooooomi/your_spotify/assets/69318685/66d879f5-26f3-4a0b-ba0e-c1d00c0bb374)

Thank you!

**Comment by Yooooomi** [comment]
Your mongo does not seem well am I right?

**Comment by kevinlf3** [comment]
> Your mongo does not seem well am I right?

It's not upadated to the latest version, but does not interfere.

**Comment by kevinlf3** [comment]
I tested to upload the file with only one song, the JSON file only weighs 1kb and upload succesfully.

I think there is a limitation of the file weight or the ammount of songs you can import.

I hope I can help you!

**Comment by Yooooomi** [comment]
If you're using nginx, there is a default limit that you have to override for the api reverse proxy.

**Comment by kevinlf3** [comment]
> If you're using nginx, there is a default limit that you have to override for the api reverse proxy.

Do you know how to do that?

**Comment by Yooooomi** [comment]
There is a parameter you can add to the location definition of your api: https://stackoverflow.com/a/37916740/5641146

**Comment by kevinlf3** [comment]
> There is a parameter you can add to the location definition of your api: https://stackoverflow.com/a/37916740/5641146

Thank you, It works!
