### ISSUE TITLE
login screen briefly appear before the whole site becomes just a dark blue

### ISSUE THREAD

**Issue by TheoQc** [Yooooomi/your_spotify#56]
So far I did not manage to get the site running... 

At first it was saying the registration were off, but it was due to a bad your_spotify_client API_ENDPOINT which was my local one.
Now that I point to the external one, it seems to go slightly further but during the load of the site, I see the login screen that quickly get replace by a dark blue page.

Looking at the javascript console, I have an error in mySite/static/js/components/SearchBar/index.js on "{results.map(r => (" where results appears to be a string of the html, and thus with no map function which is the javascript error.

content of results : "<!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="icon" href="/favicon.ico"/><meta name="viewport" content="width=device-wi..."

What could be wrong? Looking at my docker logs I don't see any errors, but again, neither was I when my API_ENDPOINT was local.

**Comment by Yooooomi** [comment]
Hello! 
Can you post here the docker-compose file you're using? Please tell me what browser you're using.
Thanks a lot 🙂

**Comment by TheoQc** [comment]
I tried chrome and edge with the same behaviour.

here for my docker-compose.yml
`version: "3"

services:
  app:
    container_name: yourspotify_server
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8091:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=http://192.168.10.222:8091                                    #visible internally, different than 
      - CLIENT_ENDPOINT=http://192.168.10.222:3000                              #visible internally
      - SPOTIFY_PUBLIC=df2************************1d658
      - SPOTIFY_SECRET=eb5************************05f26
      #- CORS=http://192.168.10.222:3000,http://localhost:3001	          #same result
      - CORS=all	
      #- MONGO_ENDPOINT=mongodb://mongo:27017/your_spotify      #can it be useful?

  mongo:
    container_name: yourspotify_mongo
    image: mongo
    volumes:
      - ${HOME}/docker/yourSpotify:/data/db

  web:
    container_name: yourspotify_web
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      - API_ENDPOINT=https://spot.mydomain.com/     #visible externally
`

It wasn't clear for me from the sample yml what needed to be visible locally and/or externally, so in spotify Redirect URIs I added both.

Just wandering, could'nt both container be packaged together and thus, only relying on a mongo container, at the same time removing a couple of possible mis-configurations.

Thank you for your time !

**Comment by Yooooomi** [comment]
At first sight, it seems that your web application points to a public endpoint while the server points to a local address. I would say either set both to have a public endpoint or both use the local 192.168.x.x thing.

As for the 2 containers I see your point, but in my opinion it's better to split since you don't always want to host the two services at the same place.

**Comment by TheoQc** [comment]
Unfortunately, still no luck.  

Having both pointing to the local adress will yield the error message in red
> Could not retrieve the global preferences of the application

On the other hand having both pointing to the external url will still give the same javascript error in SearchBar/index.js.

Fair enough for the possibility to host client/server on 2 different places :)

**Comment by Yooooomi** [comment]
The string you're receiving instead of real results for the search bar is an html page. Something tells me that the client is requesting itself and not the backend.
Since you won't write publicly your domain, can you post the updated docker-compose for a local use? The backend requested leads to a static website server.
Also, once everything is set up, can you post the result of a `curl` to both your front and backend.
Frontend should send back the html page and the backend will send `Hello !` on `/`

**Comment by Yooooomi** [comment]
@TheoQc Any news on this? We had the a similar issue there #59 have a look :)

**Comment by TheoQc** [comment]
I'll get back to it over the holydays ;) I'll try with the ip like in #59.

**Comment by Yooooomi** [comment]
Your issue is the same as #59. The client is requesting itself and not the backend. I'll close this for now since your issue is either
- you have a wrong docker-compose and this is solved in #59
- you have a wrong reverse proxy configuration and this is not in the scope of this project

If you still have issues feel free to reopen
