### ISSUE TITLE
Mono-container?

### ISSUE THREAD

**Issue by oxodao** [Yooooomi/your_spotify#77]
Hi!

I was wondering why did you make the choice to use two container instead of a single one. Apps should indeed be separated in multiple containers but here its technically only one app. You could definitely build the frontend, embed it in the API container which would serve it too, and the api could be prefixed by /api. That would be easier for the user as there is no need for CORS / things like this. 
Plus while in dev, you can use the `proxy` argument in your package.json to point to the API container.

The only point to having this in multiple containers would be if you are using this at scale and putting the React app on something like a CDN, is this the case?

If you want to stick with this, you may want to use nginx to serve the static file and do a multi-stage build for the frontend as this would be more lightweight on resources

**Comment by Yooooomi** [comment]
Hello! Thanks for your feedback.

I think I prefer multi container for a few reasons:
- You can use a common mongo database for other services
- You can have the server and the client running on two different devices
- Not every service is running concurrently in the same container
- Not a fairly comlpex bash script to launch every service

I don't think having three containers instead of one is really heavier though.
I do not want to implement an nginx container in it since I want to deliver the minimum for YourSpotify to work. I myself use nginx but I have one nginx for all my self hosted apps, so one in YourSpotify would not make sense.
As for CORS, I do not think this is something important to consider since this is always a problem 🙃.

Maybe I'll change my mind passing by some other projects that do mono container but for the moment I have a quite strong opinion on why I chose this.

If you feel like this is nonsense to you I would be very happy to discuss some points with you here. If you feel like you had an answer feel free to close this issue.

**Comment by oxodao** [comment]
Well I didn't mean to embed mongo in it too, I understand the confusion sorry. I absolutely wouldn't want it to be in the same container and we have the same opinion on this.

Concerning the frontend though, the best would be to build the client image, and make the server image embed it through multi-stage build, optionally disabled through config. This would let most of us run it by itself since the majority of the users would see no benefits from the split.

CORS would absoluetly not be an issue in this case as everything would be on the same domain.

Doing so would not require any different start script and would simplify the setup for most of your target audience, without preventing advanced users to do whatever they want.

I did not do much server-side JS so I'm not sure how you could implement this regarding the server base_url but I guess it would not be that hard to inject a variable in the HTML served that would set the api url

**Comment by Yooooomi** [comment]
I see your point there. Since it would require many people to change their image in their compose file, let's list the pros to make it clear.
- 2 entries instead of 3 currently in the compose file
- No CORS variable, determined by the API_ENDPOINT
- A single API_ENDPOINT variable

Also if understand correctly, you would only set one endpoint and have a reverse proxy setting the server on /api and the client on /

**Comment by oxodao** [comment]
It indeed would require existing users to update their config so I understand if you're reluctant to implement this. 

No need for reverse proxy as express supports serving static files. 

What I'm doing in my software (those are written in golang but they follow the same principles), is that I have a subrouter "/api" registered first, and everything not matching this route will serve a static embedded folder, which is the React's build folder

A compromise could be that the internal serving of the app would be a "false by default" flag (but still explained in the readme / default docker-compose example) that would not serve the app and keep everything as they are now. This would let existing users continue to use their setup without any modifications, but would enables new user to have a simplified setup workflow (thus enabling less tech savy users to setup this software without having to understand what CORS are, or worse, setting them to ALL just to fix issues they could encounter not knowning what this is doing, nor having special reverse-proxy setup, they would simply proxy_pass to the only exposed port and be ready to go)

**Comment by Yooooomi** [comment]
I don't think there are enough qol improvements to move all the users toward a new config. Plus the fact that it would require a migration guide.
